name: Publish hosby-cli to npm

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build-and-publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # For push tags
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Install dependencies
        run: npm ci

      - name: Run checks
        run: npm run check

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

      - name: Find version bump type
        id: version_bump
        run: |
          # Get PR title or merge commit message
          if [ "${{ github.event.pull_request.title }}" != "" ]; then
            COMMIT_MSG="${{ github.event.pull_request.title }}"
            echo "Using PR title: $COMMIT_MSG"
          else
            COMMIT_MSG=$(git log -1 --pretty=%B)
            echo "Using commit message: $COMMIT_MSG"
          fi
          
          # Determine bump type based on message
          if echo "$COMMIT_MSG" | grep -qE "BREAKING CHANGE|major:"; then
            echo "bump_type=major" >> $GITHUB_OUTPUT
            echo "Version bump: MAJOR"
          elif echo "$COMMIT_MSG" | grep -qE "feat:|feature:|minor:"; then
            echo "bump_type=minor" >> $GITHUB_OUTPUT
            echo "Version bump: MINOR"
          else
            echo "bump_type=patch" >> $GITHUB_OUTPUT
            echo "Version bump: PATCH"
          fi

      - name: Bump version
        run: |
          BUMP_TYPE="${{ steps.version_bump.outputs.bump_type }}"
          echo "Bumping version with type: $BUMP_TYPE"
          npm version $BUMP_TYPE --no-git-tag-version
          
          # Get new version
          NEW_VERSION=$(node -p "require('./package.json').version")
          echo "New version: $NEW_VERSION"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Commit version bump
        run: |
          git add package.json
          git commit -m "chore: bump version to v${{ env.NEW_VERSION }} [skip ci]"
          git tag "v${{ env.NEW_VERSION }}"

      - name: Push changes and tags
        run: |
          git push origin main
          git push origin "v${{ env.NEW_VERSION }}"

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ env.NEW_VERSION }}"
          release_name: "Release v${{ env.NEW_VERSION }}"
          body: |
            ## Changes in v${{ env.NEW_VERSION }}
            
            Auto-generated release from commit: ${{ github.event.head_commit.message }}
            
            **Full Changelog**: https://github.com/${{ github.repository }}/compare/v${{ env.PREVIOUS_VERSION }}...v${{ env.NEW_VERSION }}
          draft: false
          prerelease: false